# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.7.0"
    docker:
      repo: "puppetlabs/docker"
      ref: "10.4.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "9.1.0"
    yumrepo:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.2.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "9.1.0"
    dockerapp:
      repo: "ffquintella/dockerapp"
      ref: "1.6.0"
